### ISSUE TITLE
PE issuse

### ISSUE THREAD

**Issue by MichaelZH24** [GenomicParisCentre/eoulsan#10]
The mapping step can only use one fastq file and there is no parameters refer to PE in Map reads module. It seems that eoulsan doesn't support the PE data?

**Comment by jourdren** [comment]
Dear MichaelZH24,

If you want use Eoulsan to perform PE mapping, you need to set the input FASTQ files for your sample in the "Reads" column of your design file like: "[s1a.fq.bz2,s1b.fq.bz2]" instead of "s1a.fq.bz2" if you are in single end mode.

Eoulsan will automatically handle this files in PE mode for both, read filtering and mapping.

Regards,

Laurent.
