### ISSUE TITLE
windows and mac OS support

### ISSUE THREAD

**Issue by gouarin** [GenomicParisCentre/eoulsan#4]
Hi,

I organize a workshop about conda in two weeks and an attendee gives the eoulsan package as an example to build a conda package. I saw a recipe exists on bioconda but it's not exactly how I want to make it. I prefer to let maven compiles the project for a given platform.

So eoulsan compiles well on windows. I wrote a batch file to call it. The only problem that remains is that I have the following error

```
Error: The info of eoulsan is not available for your platform. Required platforms: Linux/x86_64, Linux/amd64.
```

Is it a limitation of your package because you didn't test it on windows or is it because some dependencies are not available on windows ?

Just to know if I continue the conda recipe or not.

**Comment by jourdren** [comment]
Hi,

Eoulsan can be only launched on a Linux because some step (like the mapping step) requires external tools that usually not exists on Windows. Moreover Eoulsan code use hard coded Unix '/' separator in paths that can lead to errors with Windows.

However, I think that you can use Eoulsan with the latest version of Windows 10 using the Windows Subsystem for Linux (WSL) and Linux distribution (like Ubuntu) on the Windows Store.

Laurent.

**Comment by gouarin** [comment]
Thanks.
