### ISSUE TITLE
path not available while executing eoulsan

### ISSUE THREAD

**Issue by GMaciag** [GenomicParisCentre/eoulsan#7]
Hi, 

I have tried to follow the 10x Genomics tutorial on my own data. However, when trying to run the analysis I get the following error:
```
=== Eoulsan Error ===
Error while executing eoulsan: Requirement for step "step12singlecellexperiment" is not available: path
```
I once also got similar error for `"step7multiqc"`. I looked around, but I couldn't find out what could be the cause of the issue or how to fix it. Could anyone help me? 

I'm trying to run eoulsan without using docker, if that makes a difference. 

Thanks!

**Comment by jourdren** [comment]
Hi,

The "step12singlecellexperiment" step works only in Docker mode for Eoulsan 2.3. This bug has been fixed in Eoulsan master.

The step 7, you need to install MultiQC on your system and it must be in the PATH environment variable. 

The branch2.3 of the Git repository contains many fixes for Eoulsan 2.3 that has been backported from master. The master branch of Eoulsan is stable and pass all (190+) analysis tests, you can compile it and use it.

We hope to publish a new version of Eoulsan in the next 2 months.

Best regards,

Laurent.
